services:

  server:
    image: ghcr.io/ironcalc/ironcalc-server:0.6.0
    container_name: ironcalc-server
    restart: unless-stopped
    
  caddy:
    image: ghcr.io/ironcalc/ironcalc-caddy:0.6.0
    container_name: ironcalc-caddy
    ports:
      - "8200:2080"
    restart: unless-stopped
